pull_request_rules:
  - name: automatic merge with 1 approvals
    conditions:
      - "#approved-reviews-by>=1"
      - base=master
      - label=auto-merge
    actions:
      merge:
        strict: smart
        method: squash
      delete_head_branch: {}
